"""initial schema

Revision ID: aa9d09ab32d5
Revises: 
Create Date: 2026-08-25 02:16:16.941621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa9d09ab32d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('inbound_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inbound_email')
    )
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    op.create_table('loads',
    sa.Column('load_number', sa.String(length=100), nullable=False),
    sa.Column('carrier_name', sa.String(length=255), nullable=False),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('equipment_type', sa.String(length=100), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('linehaul_rate', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fuel_surcharge_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('detention_terms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('accessorials_allowed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'MATCHED', 'CLOSED', name='load_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'load_number', name='uq_loads_company_load_number')
    )
    op.create_index(op.f('ix_loads_company_id'), 'loads', ['company_id'], unique=False)
    op.create_index(op.f('ix_loads_load_number'), 'loads', ['load_number'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'REVIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'email', name='uq_users_company_email')
    )
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('SYSTEM', 'USER', name='audit_actor_type'), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_company_id'), 'audit_logs', ['company_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_type'), 'audit_logs', ['event_type'], unique=False)
    op.create_table('documents',
    sa.Column('load_id', sa.UUID(), nullable=True),
    sa.Column('doc_type', sa.Enum('RATE_CONFIRMATION', 'INVOICE', 'POD', name='document_type'), nullable=False),
    sa.Column('source', sa.Enum('EMAIL', 'UPLOAD', name='document_source'), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('storage_key', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', name='document_status'), nullable=False),
    sa.Column('extracted_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extraction_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_company_id'), 'documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_documents_content_hash'), 'documents', ['content_hash'], unique=False)
    op.create_index(op.f('ix_documents_load_id'), 'documents', ['load_id'], unique=False)
    op.create_table('line_items',
    sa.Column('load_id', sa.UUID(), nullable=False),
    sa.Column('invoice_document_id', sa.UUID(), nullable=False),
    sa.Column('line_type', sa.Enum('LINEHAUL', 'FUEL_SURCHARGE', 'DETENTION', 'ACCESSORIAL', 'OTHER', name='line_item_type'), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('billed_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('match_status', sa.Enum('CLEAN', 'DISCREPANCY', 'NEEDS_INFO', name='match_status'), nullable=False),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invoice_document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_company_id'), 'line_items', ['company_id'], unique=False)
    op.create_index(op.f('ix_line_items_invoice_document_id'), 'line_items', ['invoice_document_id'], unique=False)
    op.create_index(op.f('ix_line_items_load_id'), 'line_items', ['load_id'], unique=False)
    op.create_table('reviews',
    sa.Column('load_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'DISPUTE', 'OVERRIDE', name='review_action'), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['load_id'], ['loads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_company_id'), 'reviews', ['company_id'], unique=False)
    op.create_index(op.f('ix_reviews_load_id'), 'reviews', ['load_id'], unique=False)
    op.create_index(op.f('ix_reviews_reviewer_id'), 'reviews', ['reviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_reviewer_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_load_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_company_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_line_items_load_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_invoice_document_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_company_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_documents_load_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_content_hash'), table_name='documents')
    op.drop_index(op.f('ix_documents_company_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_audit_logs_event_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_company_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_loads_load_number'), table_name='loads')
    op.drop_index(op.f('ix_loads_company_id'), table_name='loads')
    op.drop_table('loads')
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # Alembic's autogenerated DROP TABLEs above don't drop the Postgres ENUM
    # types those columns used (a DROP TABLE never implies DROP TYPE, since
    # a type can in principle be shared by other tables) — without this,
    # `downgrade` doesn't actually reverse `upgrade`: a downgrade followed
    # by another upgrade fails with "type already exists". Every enum below
    # is unique to one column, so it's always safe to drop here.
    for enum_name in (
        "review_action",
        "match_status",
        "line_item_type",
        "document_status",
        "document_source",
        "document_type",
        "audit_actor_type",
        "user_role",
        "load_status",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
