"""add carrier broker portal

Revision ID: c8a3f6e22dba
Revises: aa9d09ab32d5
Create Date: 2026-08-26 01:37:07.692730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a3f6e22dba'
down_revision: Union[str, None] = 'aa9d09ab32d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # New AuditActorType.CARRIER value — broker-originated audit rows (a
    # broker responding to a Needs Info flag, or uploading a corrected
    # document) get actor_type=CARRIER with actor_id left NULL (CarrierUser
    # isn't FK'able from audit_logs.actor_id, which points at users.id
    # only — see app/services/audit_service.py for how the carrier's name
    # is instead recorded directly in that row's `details`). Postgres enum
    # values can only be added with ALTER TYPE, never via a plain column
    # change, and must run before anything below could reference it.
    op.execute("ALTER TYPE audit_actor_type ADD VALUE IF NOT EXISTS 'CARRIER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carriers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'name', name='uq_carriers_company_name')
    )
    op.create_index(op.f('ix_carriers_company_id'), 'carriers', ['company_id'], unique=False)
    op.create_table('carrier_users',
    sa.Column('carrier_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['carriers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('carrier_id', 'email', name='uq_carrier_users_carrier_email')
    )
    op.create_index(op.f('ix_carrier_users_carrier_id'), 'carrier_users', ['carrier_id'], unique=False)
    op.create_index(op.f('ix_carrier_users_email'), 'carrier_users', ['email'], unique=False)
    op.add_column('loads', sa.Column('carrier_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_loads_carrier_id'), 'loads', ['carrier_id'], unique=False)
    op.create_foreign_key('fk_loads_carrier_id_carriers', 'loads', 'carriers', ['carrier_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_loads_carrier_id_carriers', 'loads', type_='foreignkey')
    op.drop_index(op.f('ix_loads_carrier_id'), table_name='loads')
    op.drop_column('loads', 'carrier_id')
    op.drop_index(op.f('ix_carrier_users_email'), table_name='carrier_users')
    op.drop_index(op.f('ix_carrier_users_carrier_id'), table_name='carrier_users')
    op.drop_table('carrier_users')
    op.drop_index(op.f('ix_carriers_company_id'), table_name='carriers')
    op.drop_table('carriers')
    # ### end Alembic commands ###

    # Note: Postgres has no ALTER TYPE ... DROP VALUE, so downgrade()
    # cannot cleanly remove 'carrier' from audit_actor_type — same
    # limitation the initial migration's downgrade() comment calls out for
    # dropping enum TYPEs outright. Leaving the value in place on downgrade
    # is harmless: nothing in the pre-carrier-portal code ever writes it.
